;this file for FamiTone2 library generated by text2data tool

DEMO_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cc,$ca,$c6,$c4,$c2,$c1,$00,$06


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$06,$97,$00,$85,$06,$95,$00,$83
@ref1:
	.byte $81,$06,$95,$00,$85,$06,$95,$00,$83
@ref2:
	.byte $06,$97,$00,$85,$06,$95,$00,$83
	.byte $ff,$09
	.word @ref1
@ref4:
	.byte $bf
@ref5:
	.byte $bf
@ref6:
	.byte $bf
@ref7:
	.byte $bf
@ref8:
	.byte $bf
	.byte $ff,$09
	.word @ref1
	.byte $ff,$08
	.word @ref2
	.byte $ff,$09
	.word @ref1
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref12:
	.byte $80,$74,$67,$5e,$59,$70,$67,$5e,$59,$6e,$67,$5f,$59,$71,$67,$5f
	.byte $59,$71,$63,$5c
@ref13:
	.byte $81,$54,$6d,$62,$5d,$54,$6b,$62,$5d,$54,$6d,$62,$5d,$55,$54,$55
	.byte $54,$47,$40,$3a,$85
@ref14:
	.byte $74,$67,$5e,$59,$70,$67,$5e,$59,$6e,$67,$5f,$59,$71,$67,$5f,$59
	.byte $71,$63,$5c
	.byte $ff,$15
	.word @ref13
	.byte $ff,$13
	.word @ref14
	.byte $ff,$15
	.word @ref13
	.byte $ff,$13
	.word @ref14
@ref19:
	.byte $81,$54,$6d,$62,$5d,$54,$6b,$62,$5d,$54,$6d,$62,$5d,$55,$54,$55
	.byte $54,$47,$40,$3a,$83,$00
@ref20:
	.byte $bf
@ref21:
	.byte $bf
@ref22:
	.byte $74,$66,$87,$70,$66,$87,$6e,$66,$85,$58,$85,$66,$85,$58,$85,$62
	.byte $83
@ref23:
	.byte $81,$54,$6c,$87,$54,$6a,$87,$54,$6c,$87,$54,$54,$54,$54,$83,$3a
	.byte $3a,$40,$3a,$3a,$3a,$81
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref24:
	.byte $81,$80,$2c,$99,$01,$2c,$99,$00
@ref25:
	.byte $81,$2c,$99,$01,$2c,$99,$00
	.byte $ff,$07
	.word @ref25
	.byte $ff,$07
	.word @ref25
@ref28:
	.byte $bf
@ref29:
	.byte $bf
@ref30:
	.byte $bf
@ref31:
	.byte $bf
@ref32:
	.byte $bf
	.byte $ff,$07
	.word @ref25
	.byte $ff,$07
	.word @ref25
	.byte $ff,$07
	.word @ref25
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref36:
	.byte $81,$80,$03,$1a,$1a,$0d,$1a,$1a,$03,$1a,$1a,$0c,$85,$03,$1a,$1a
	.byte $0d,$1a,$1a,$03,$1a,$1a,$0c,$83
@ref37:
	.byte $81,$03,$1a,$1a,$0d,$1a,$1a,$03,$1a,$1a,$0c,$85,$03,$1a,$1a,$0d
	.byte $1a,$1a,$03,$1a,$1a,$0c,$83
	.byte $ff,$17
	.word @ref37
	.byte $ff,$17
	.word @ref37
	.byte $ff,$17
	.word @ref37
	.byte $ff,$17
	.word @ref37
@ref42:
	.byte $81,$02,$85,$0c,$85,$02,$85,$0c,$85,$02,$85,$0c,$85,$02,$85,$0c
	.byte $83
	.byte $ff,$11
	.word @ref42
@ref44:
	.byte $81,$02,$89,$1a,$1a,$02,$8d,$03,$1a,$1a,$0d,$1a,$1a,$03,$1a,$1a
	.byte $0c,$83
	.byte $ff,$17
	.word @ref37
	.byte $ff,$17
	.word @ref37
	.byte $ff,$17
	.word @ref37
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref48:
	.byte $bf
@ref49:
	.byte $bf
@ref50:
	.byte $bf
@ref51:
	.byte $bf
@ref52:
	.byte $bf
@ref53:
	.byte $bf
@ref54:
	.byte $bf
@ref55:
	.byte $bf
@ref56:
	.byte $bf
@ref57:
	.byte $bf
@ref58:
	.byte $bf
@ref59:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
